CREATE
    EXTENSION IF NOT EXISTS "uuid-ossp";

INSERT
    INTO
        winyourlife.users(
            created_date,
            last_modified_date,
            version,
            uuid,
            email,
            password,
            is_enabled,
            ROLE
        )
    VALUES(
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user1@example.com',
        '$2a$12$LdZFfuccCDIwzNqn3jLg3.Z8Aw6g6bePh9W4Z8ipsSJvLSRp6H6FO',
        TRUE,
        'USER'
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user2@example.com',
        '$2a$12$LdZFfuccCDIwzNqn3jLg3.Z8Aw6g6bePh9W4Z8ipsSJvLSRp6H6FO',
        TRUE,
        'USER'
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user3@example.com',
        '$2a$12$LdZFfuccCDIwzNqn3jLg3.Z8Aw6g6bePh9W4Z8ipsSJvLSRp6H6FO',
        TRUE,
        'USER'
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user4@example.com',
        '$2a$12$LdZFfuccCDIwzNqn3jLg3.Z8Aw6g6bePh9W4Z8ipsSJvLSRp6H6FO',
        TRUE,
        'USER'
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'molrib1939@gmail.com',
        '$2a$12$LdZFfuccCDIwzNqn3jLg3.Z8Aw6g6bePh9W4Z8ipsSJvLSRp6H6FO',
        TRUE,
        'USER'
    );

INSERT
    INTO
        winyourlife.users_info(
            created_date,
            last_modified_date,
            version,
            uuid,
            email,
            name,
            streak,
            longest_streak,
            completed_tasks,
            avatar,
            won_days
        )
    VALUES(
        NOW(),
        NOW(),
        0,
        '123e4567-e89b-12d3-a456-426614174010',
        'user1@example.com',
        'User One',
        5,
        10,
        50,
        E'\\x',
        15
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user2@example.com',
        'User Two',
        3,
        5,
        30,
        E'\\x',
        15
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user3@example.com',
        'User Three',
        7,
        12,
        70,
        E'\\x',
        15
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'user4@example.com',
        'User Four',
        2,
        4,
        15,
        E'\\x',
        15
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        'molrib1939@gmail.com',
        'User Five',
        6,
        9,
        60,
        E'\\x',
        15
    );

INSERT
    INTO
        winyourlife.tasks(
            created_date,
            last_modified_date,
            version,
            uuid,
            user_uuid,
            task_name,
            task_image,
            is_completed,
            is_active,
            is_prepared
        )
    VALUES(
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 1',
        E'\\x',
        FALSE,
        FALSE,
        FALSE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 2',
        E'\\x',
        FALSE,
        FALSE,
        FALSE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 3',
        E'\\x',
        FALSE,
        FALSE,
        FALSE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 4',
        E'\\x',
        FALSE,
        FALSE,
        TRUE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 5',
        E'\\x',
        FALSE,
        FALSE,
        TRUE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 6',
        E'\\x',
        TRUE,
        TRUE,
        FALSE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 7',
        E'\\x',
        FALSE,
        TRUE,
        TRUE
    ),
    (
        NOW(),
        NOW(),
        0,
        uuid_generate_v4(),
        '123e4567-e89b-12d3-a456-426614174010',
        'Task 8',
        E'\\x',
        FALSE,
        TRUE,
        TRUE
    );
